// Generated by CoffeeScript 1.7.1
var compilers, getCompiler, path, through, wrap;

path = require('path');

through = require('browserify-through');

wrap = function(callback) {
  return function(err, src) {
    if (src != null) {
      src = "module.exports = " + (JSON.stringify(src));
    }
    return callback(err, src);
  };
};

compilers = {
  '.coffee': function(src, filepath, debug, callback) {
    return require('coffee-compiler').fromSource(src, {
      sourceMap: debug,
      filename: filepath,
      bare: true
    }, callback);
  },
  '.less': function(src, filepath, debug, callback) {
    return require('less-compiler').fromSource(src, {
      sourceMap: false,
      filename: filepath
    }, wrap(callback));
  },
  '.jade': function(src, filepath, debug, callback) {
    return require('jade-compiler').fromSource(src, {}, wrap(callback));
  }
};

getCompiler = function(filepath) {
  var compiler;
  return compiler = compilers[path.extname(filepath)];
};

module.exports = through({
  filter: function(filepath) {
    return getCompiler(filepath);
  },
  map: function(filepath, data, callback) {
    return getCompiler(filepath)(data, filepath, {
      debug: true
    }, callback);
  }
});
